# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  sql1:
    cmds:
      - psql -h localhost -U postgres  -a -f StrengeMettlerKuengAufg1.sql
  sql2:
    cmds:
      - psql -h localhost -U postgres  -a -f StrengeMettlerKuengAufg2.sql